### ISSUE TITLE
TLS error handshake

### ISSUE THREAD

**Issue by emmauss** [barnacs/compy#19]
using latest commit, i get this error.
`2017/06/09 07:50:01 http: TLS handshake error from 41.66.203.167:41837: read tcp 45.62.242.187:3130->41.66.203.167:41837: read: connection reset by peer
2017/06/09 07:50:01 http: TLS handshake error from 41.66.203.167:57673: read tcp 45.62.242.187:3130->41.66.203.167:57673: read: connection reset by peer
2017/06/09 07:50:03 http: TLS handshake error from 41.66.203.167:41127: read tcp 45.62.242.187:3130->41.66.203.167:41127: read: connection reset by peer
2017/06/09 07:50:04 http: TLS handshake error from 41.66.203.167:47938: read tcp 45.62.242.187:3130->41.66.203.167:47938: read: connection reset by peer
2017/06/09 07:50:05 http: TLS handshake error from 41.66.203.167:56411: read tcp 45.62.242.187:3130->41.66.203.167:56411: read: connection reset by peer
`

**Comment by andrewgaul** [comment]
Is this a regression from an earlier commit?  How did you configure compy?

**Comment by andrewgaul** [comment]
I successfully tested SSL support with the latest master.  Closing this issue due to lack of response.
