### ISSUE TITLE
mitm issue

### ISSUE THREAD

**Issue by hdid** [barnacs/compy#37]
When i run with mitm enabled, i get this:
```
# compy -ca ca.crt -cakey ca.key
not using mitm: open : no such file or directory
2018/03/11 12:11:32 compy listening on :9999
```

OS is Debian 9 x64 and go 1.10

**Comment by Koloses** [comment]
Having the same on Ubuntu 16.04

**Comment by millerlogic** [comment]
I also got this error. The error does not happen if you also provide -cert and -key options, but if you only use -ca and -cakey it happens.
