### ISSUE TITLE
Some sites give certificate error when using mitm

### ISSUE THREAD

**Issue by gnidorah** [barnacs/compy#44]
Most of https sites work ok, but some of them fail with invalid certificate error. Here's an example list:
https://vk.com
https://youtube.com/
https://support.google.com/chrome/answer/6098869

**Comment by ggramaize** [comment]
Considering the issue and the examples, it sounds like Https public Key Pinning (HPKP) just bit you.
On Firefox, the default behaviour is silently accept MITM if you installed your proxy's CA certificate by hand into the trusted CA certificate store.

Not sure if it's necessary to keep that ticket open.
